# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POBG67ndN99Tcbh4jrF9Qn-lVHQbg-R4
"""

import streamlit as st
import pandas as pd
import random
import sympy as sp
from sympy import sympify
from datetime import datetime
import os

# -------------------------
# Cargar banco
# -------------------------
@st.cache_data
def cargar_banco():
    return pd.read_excel("banco_preguntas.xlsx")

banco = cargar_banco()

st.title("Generador de Examen de Matemáticas")

# -------------------------
# Datos estudiante
# -------------------------
nombre = st.text_input("Nombre completo")
codigo = st.text_input("Código")

if nombre and codigo:

    # Semilla única
    semilla = hash(nombre + codigo)
    random.seed(semilla)

    st.subheader("Examen")

    preguntas = banco.sample(5, random_state=semilla)

    respuestas_estudiante = {}
    puntaje_total = 0
    puntos_posibles = 0

    for index, row in preguntas.iterrows():
        st.write(f"### {row['id']} - ({row['puntos']} puntos)")
        st.write(row["enunciado"])

        respuesta = st.text_input("Respuesta:", key=row["id"])
        respuestas_estudiante[row["id"]] = respuesta
        puntos_posibles += row["puntos"]

    if st.button("Calificar"):

        for index, row in preguntas.iterrows():
            resp_est = respuestas_estudiante[row["id"]]
            resp_correcta = str(row["respuesta"])
            tipo = row["tipo"]

            correcta = False

            try:
                if tipo == "numerica":
                    tol = float(row["tolerancia"])
                    if abs(float(resp_est) - float(sp.N(sp.sympify(resp_correcta)))) < tol:
                        correcta = True

                elif tipo == "simbolica":
                    expr1 = sympify(resp_est.replace("^","**"))
                    expr2 = sympify(resp_correcta.replace("^","**"))
                    if sp.simplify(expr1 - expr2) == 0:
                        correcta = True

                elif tipo == "opcion_multiple":
                    if resp_est.strip().upper() == resp_correcta.strip().upper():
                        correcta = True

            except:
                correcta = False

            if correcta:
                puntaje_total += row["puntos"]

        nota = round((puntaje_total / puntos_posibles) * 5, 2)

        st.success(f"Nota final: {nota} / 5.0")

        # Guardar en Excel
        registro = {
            "fecha": datetime.now(),
            "nombre": nombre,
            "codigo": codigo,
            "nota": nota
        }

        archivo_notas = "notas.xlsx"

        if os.path.exists(archivo_notas):
            df_notas = pd.read_excel(archivo_notas)
            df_notas = pd.concat([df_notas, pd.DataFrame([registro])])
        else:
            df_notas = pd.DataFrame([registro])

        df_notas.to_excel(archivo_notas, index=False)